# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PlasmaCtrlDlg.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PlasmaCtrlDlg(object):
    def setupUi(self, PlasmaCtrlDlg):
        PlasmaCtrlDlg.setObjectName("PlasmaCtrlDlg")
        PlasmaCtrlDlg.setWindowModality(QtCore.Qt.ApplicationModal)
        PlasmaCtrlDlg.resize(636, 456)
        self.InitalizeButton = QtWidgets.QPushButton(PlasmaCtrlDlg)
        self.InitalizeButton.setGeometry(QtCore.QRect(400, 400, 94, 27))
        self.InitalizeButton.setObjectName("InitalizeButton")
        self.IonGaugeCtrl = QtWidgets.QGroupBox(PlasmaCtrlDlg)
        self.IonGaugeCtrl.setGeometry(QtCore.QRect(390, 30, 191, 171))
        self.IonGaugeCtrl.setFlat(False)
        self.IonGaugeCtrl.setObjectName("IonGaugeCtrl")
        self.label = QtWidgets.QLabel(self.IonGaugeCtrl)
        self.label.setGeometry(QtCore.QRect(10, 50, 31, 19))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.IonGaugeCtrl)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 31, 20))
        self.label_2.setObjectName("label_2")
        self.IONGauge = QtWidgets.QLineEdit(self.IonGaugeCtrl)
        self.IONGauge.setGeometry(QtCore.QRect(50, 40, 131, 31))
        self.IONGauge.setObjectName("IONGauge")
        self.GaugeA = QtWidgets.QLineEdit(self.IonGaugeCtrl)
        self.GaugeA.setGeometry(QtCore.QRect(50, 70, 131, 31))
        self.GaugeA.setObjectName("GaugeA")
        self.GaugeB = QtWidgets.QLineEdit(self.IonGaugeCtrl)
        self.GaugeB.setGeometry(QtCore.QRect(50, 100, 131, 31))
        self.GaugeB.setObjectName("GaugeB")
        self.label_15 = QtWidgets.QLabel(self.IonGaugeCtrl)
        self.label_15.setGeometry(QtCore.QRect(10, 110, 31, 19))
        self.label_15.setObjectName("label_15")
        self.SOLENOID = QtWidgets.QGroupBox(PlasmaCtrlDlg)
        self.SOLENOID.setGeometry(QtCore.QRect(20, 10, 251, 131))
        self.SOLENOID.setObjectName("SOLENOID")
        self.label_3 = QtWidgets.QLabel(self.SOLENOID)
        self.label_3.setGeometry(QtCore.QRect(20, 60, 21, 19))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.SOLENOID)
        self.label_4.setGeometry(QtCore.QRect(50, 30, 64, 19))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.SOLENOID)
        self.label_5.setGeometry(QtCore.QRect(150, 30, 64, 19))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.SOLENOID)
        self.label_6.setGeometry(QtCore.QRect(23, 90, 16, 20))
        self.label_6.setObjectName("label_6")
        self.SOLENOIDVSet = QtWidgets.QLineEdit(self.SOLENOID)
        self.SOLENOIDVSet.setGeometry(QtCore.QRect(40, 50, 81, 31))
        self.SOLENOIDVSet.setObjectName("SOLENOIDVSet")
        self.SOLENOIDISet = QtWidgets.QLineEdit(self.SOLENOID)
        self.SOLENOIDISet.setGeometry(QtCore.QRect(40, 80, 81, 31))
        self.SOLENOIDISet.setObjectName("SOLENOIDISet")
        self.SOLENOIDVRead = QtWidgets.QLineEdit(self.SOLENOID)
        self.SOLENOIDVRead.setGeometry(QtCore.QRect(130, 50, 91, 31))
        self.SOLENOIDVRead.setObjectName("SOLENOIDVRead")
        self.SOLENOIDIRead = QtWidgets.QLineEdit(self.SOLENOID)
        self.SOLENOIDIRead.setGeometry(QtCore.QRect(130, 80, 91, 31))
        self.SOLENOIDIRead.setObjectName("SOLENOIDIRead")
        self.SOLENOID_2 = QtWidgets.QGroupBox(PlasmaCtrlDlg)
        self.SOLENOID_2.setGeometry(QtCore.QRect(20, 150, 251, 131))
        self.SOLENOID_2.setObjectName("SOLENOID_2")
        self.label_7 = QtWidgets.QLabel(self.SOLENOID_2)
        self.label_7.setGeometry(QtCore.QRect(20, 60, 21, 19))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.SOLENOID_2)
        self.label_8.setGeometry(QtCore.QRect(50, 30, 64, 19))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.SOLENOID_2)
        self.label_9.setGeometry(QtCore.QRect(150, 30, 64, 19))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.SOLENOID_2)
        self.label_10.setGeometry(QtCore.QRect(23, 90, 16, 20))
        self.label_10.setObjectName("label_10")
        self.DISCHARGEVSet = QtWidgets.QLineEdit(self.SOLENOID_2)
        self.DISCHARGEVSet.setGeometry(QtCore.QRect(40, 50, 81, 31))
        self.DISCHARGEVSet.setObjectName("DISCHARGEVSet")
        self.DISCHARGEISet = QtWidgets.QLineEdit(self.SOLENOID_2)
        self.DISCHARGEISet.setGeometry(QtCore.QRect(40, 80, 81, 31))
        self.DISCHARGEISet.setObjectName("DISCHARGEISet")
        self.DISCHARGEVRead = QtWidgets.QLineEdit(self.SOLENOID_2)
        self.DISCHARGEVRead.setGeometry(QtCore.QRect(130, 50, 91, 31))
        self.DISCHARGEVRead.setObjectName("DISCHARGEVRead")
        self.DISCHARGEIRead = QtWidgets.QLineEdit(self.SOLENOID_2)
        self.DISCHARGEIRead.setGeometry(QtCore.QRect(130, 80, 91, 31))
        self.DISCHARGEIRead.setObjectName("DISCHARGEIRead")
        self.SOLENOID_3 = QtWidgets.QGroupBox(PlasmaCtrlDlg)
        self.SOLENOID_3.setGeometry(QtCore.QRect(20, 290, 251, 131))
        self.SOLENOID_3.setObjectName("SOLENOID_3")
        self.label_11 = QtWidgets.QLabel(self.SOLENOID_3)
        self.label_11.setGeometry(QtCore.QRect(20, 60, 21, 19))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.SOLENOID_3)
        self.label_12.setGeometry(QtCore.QRect(50, 30, 64, 19))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.SOLENOID_3)
        self.label_13.setGeometry(QtCore.QRect(150, 30, 64, 19))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.SOLENOID_3)
        self.label_14.setGeometry(QtCore.QRect(23, 90, 16, 20))
        self.label_14.setObjectName("label_14")
        self.HEATERVSet = QtWidgets.QLineEdit(self.SOLENOID_3)
        self.HEATERVSet.setGeometry(QtCore.QRect(40, 50, 81, 31))
        self.HEATERVSet.setObjectName("HEATERVSet")
        self.HEATERISet = QtWidgets.QLineEdit(self.SOLENOID_3)
        self.HEATERISet.setGeometry(QtCore.QRect(40, 80, 81, 31))
        self.HEATERISet.setObjectName("HEATERISet")
        self.HEATERVRead = QtWidgets.QLineEdit(self.SOLENOID_3)
        self.HEATERVRead.setGeometry(QtCore.QRect(130, 50, 91, 31))
        self.HEATERVRead.setObjectName("HEATERVRead")
        self.HEATERIRead = QtWidgets.QLineEdit(self.SOLENOID_3)
        self.HEATERIRead.setGeometry(QtCore.QRect(130, 80, 91, 31))
        self.HEATERIRead.setObjectName("HEATERIRead")
        self.CloseButton = QtWidgets.QPushButton(PlasmaCtrlDlg)
        self.CloseButton.setGeometry(QtCore.QRect(290, 400, 94, 27))
        self.CloseButton.setObjectName("CloseButton")
        self.HeatCathodeButton = QtWidgets.QPushButton(PlasmaCtrlDlg)
        self.HeatCathodeButton.setGeometry(QtCore.QRect(280, 330, 94, 27))
        self.HeatCathodeButton.setObjectName("HeatCathodeButton")
        self.CoolCathodeButton = QtWidgets.QPushButton(PlasmaCtrlDlg)
        self.CoolCathodeButton.setGeometry(QtCore.QRect(280, 360, 94, 27))
        self.CoolCathodeButton.setObjectName("CoolCathodeButton")
        self.label_16 = QtWidgets.QLabel(PlasmaCtrlDlg)
        self.label_16.setGeometry(QtCore.QRect(480, 210, 81, 16))
        self.label_16.setObjectName("label_16")
        self.PlasmaStatus = QtWidgets.QLineEdit(PlasmaCtrlDlg)
        self.PlasmaStatus.setGeometry(QtCore.QRect(410, 230, 221, 41))
        self.PlasmaStatus.setObjectName("PlasmaStatus")
        self.UpdateButton = QtWidgets.QPushButton(PlasmaCtrlDlg)
        self.UpdateButton.setGeometry(QtCore.QRect(510, 400, 94, 27))
        self.UpdateButton.setObjectName("UpdateButton")

        self.retranslateUi(PlasmaCtrlDlg)
        self.InitalizeButton.clicked.connect(PlasmaCtrlDlg.OnInitializeClicked)
        self.SOLENOIDVSet.returnPressed.connect(PlasmaCtrlDlg.OnSOLENOIDVSetChanged)
        self.SOLENOIDISet.returnPressed.connect(PlasmaCtrlDlg.OnSOLENOIDISetChanged)
        self.DISCHARGEISet.returnPressed.connect(PlasmaCtrlDlg.OnDISCHARGEISetChanged)
        self.DISCHARGEVSet.returnPressed.connect(PlasmaCtrlDlg.OnDISCHARGEVSetChanged)
        self.HEATERISet.returnPressed.connect(PlasmaCtrlDlg.OnHEATERISetChanged)
        self.HEATERVSet.returnPressed.connect(PlasmaCtrlDlg.OnHEATERVSetChanged)
        self.CloseButton.clicked.connect(PlasmaCtrlDlg.OnCloseButtonClicked)
        self.CoolCathodeButton.clicked.connect(PlasmaCtrlDlg.OnCoolCathodeClicked)
        self.HeatCathodeButton.clicked.connect(PlasmaCtrlDlg.OnHeatCathodeClicked)
        self.UpdateButton.clicked.connect(PlasmaCtrlDlg.OnUpdateClicked)
        QtCore.QMetaObject.connectSlotsByName(PlasmaCtrlDlg)

    def retranslateUi(self, PlasmaCtrlDlg):
        _translate = QtCore.QCoreApplication.translate
        PlasmaCtrlDlg.setWindowTitle(_translate("PlasmaCtrlDlg", "Plasma Ctrls"))
        self.InitalizeButton.setText(_translate("PlasmaCtrlDlg", "Initialize"))
        self.IonGaugeCtrl.setTitle(_translate("PlasmaCtrlDlg", "Terranova 934"))
        self.label.setText(_translate("PlasmaCtrlDlg", "IG:"))
        self.label_2.setText(_translate("PlasmaCtrlDlg", "A:"))
        self.label_15.setText(_translate("PlasmaCtrlDlg", "B:"))
        self.SOLENOID.setTitle(_translate("PlasmaCtrlDlg", "Solenoid"))
        self.label_3.setText(_translate("PlasmaCtrlDlg", "V: "))
        self.label_4.setText(_translate("PlasmaCtrlDlg", "Set Val"))
        self.label_5.setText(_translate("PlasmaCtrlDlg", "RB Val"))
        self.label_6.setText(_translate("PlasmaCtrlDlg", "I:"))
        self.SOLENOID_2.setTitle(_translate("PlasmaCtrlDlg", "Discharge"))
        self.label_7.setText(_translate("PlasmaCtrlDlg", "V: "))
        self.label_8.setText(_translate("PlasmaCtrlDlg", "Set Val"))
        self.label_9.setText(_translate("PlasmaCtrlDlg", "RB Val"))
        self.label_10.setText(_translate("PlasmaCtrlDlg", "I:"))
        self.SOLENOID_3.setTitle(_translate("PlasmaCtrlDlg", "Heater"))
        self.label_11.setText(_translate("PlasmaCtrlDlg", "V: "))
        self.label_12.setText(_translate("PlasmaCtrlDlg", "Set Val"))
        self.label_13.setText(_translate("PlasmaCtrlDlg", "RB Val"))
        self.label_14.setText(_translate("PlasmaCtrlDlg", "I:"))
        self.CloseButton.setText(_translate("PlasmaCtrlDlg", "Close"))
        self.HeatCathodeButton.setText(_translate("PlasmaCtrlDlg", "Heat Cathode"))
        self.CoolCathodeButton.setText(_translate("PlasmaCtrlDlg", "Cool Cathode"))
        self.label_16.setText(_translate("PlasmaCtrlDlg", "Current Status"))
        self.UpdateButton.setText(_translate("PlasmaCtrlDlg", "Update"))

